
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: kad-controller
  namespace: flux-system
spec:
  interval: 1m
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://quay.io/kubotal/charts/kad-controller
  ref:
    semver: "= 0.5.0-snapshot"


---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: kad-controller
  namespace: flux-system
spec:
  interval: 1m
  serviceAccountName: kustomize-controller
  targetNamespace: flux-system
  storageNamespace: flux-system
  releaseName: kad-controller
  timeout: 5m
  install:
    remediation:
      retries: 30
      remediateLastFailure: true
  upgrade:
    remediation:
      retries: 30
      remediateLastFailure: true
  chartRef:
    kind: OCIRepository
    name: kad-controller
    namespace: flux-system
  values:
    config:
      sweepPeriod: 2m # TODO: Set to 1h after setup
      cleaner:
        enabled: true
        enforced: true
      primarySources:
        - location: /kad-controller
          kadFiles:
            - tmpl
        - name: flux-system
          namespace: flux-system
          kadFiles:
            - clusters/kind/mbp64/kubo4/system
            - clusters/kind/mbp64/kubo4/deployments
            - clusters/context.yaml
            - clusters/kind/context.yaml
            - clusters/kind/mbp64/context.yaml
            - clusters/kind/mbp64/kubo4/context.yaml
            - kad-components.yaml
    logger:
      mode: dev
      level: info
    image:
      pullPolicy: Always
    dryRun: false
    noApply: false

