
extraNamespaces:
  - name: contexts

contexts:
  - name: global
    namespace: contexts
    parents: []
    context:
      # This is for cert-manager's users
      certificateIssuer:
        public: cluster-odp
        internal: cluster-internal
    protected: true
  - name: kind
    namespace: contexts
    description: For all kind based clusters
    parents:
      - name: global
    context:
      storageClass:
        data: standard
        workspace: standard
      ingress:
        className: nginx
    protected: true
  - name: cluster
    namespace: contexts
    description: Context specific to the cluster 'kubo1'
    parents:
      - name: kind
    context:
      cluster:
        name: kubo1
        domain: kubo1.mbp
      ingress:
        hostPostfix: ingress.kubo1.mbp
        kubernetes:
          enabled: true
    protected: true

config:
  kuboAppRedirects:
    - oldPrefix: quay.io/kubocd/
      newPrefix: host.docker.internal:5001/
      certSecretRef:
        name: ca-odp
     # Other OciRepositorySpec elements
  clusterRoles:
    - storage
  imageRedirects:

    - oldPrefix: ghcr.io/stefanprodan/podinfo
      newPrefix: host.docker.internal:5001/stefanprodan/podinfo

    - oldPrefix: docker.io/bitnami/redis
      newPrefix: host.docker.internal:5001/bitnami/redis

    - oldPrefix: ghcr.io/joeferner/redis-commander
      newPrefix: host.docker.internal:5001/joeferner/redis-commander

    - oldPrefix: ghcr.io/cloudnative-pg/
      newPrefix: host.docker.internal:5001/cloudnative-pg

    - oldPrefix: quay.io/jetstack
      newPrefix: host.docker.internal:5001/jetstack

    - oldPrefix: quay.io/metallb
      newPrefix: host.docker.internal:5001/metallb

    - oldPrefix: quay.io/frrouting/frr
      newPrefix: host.docker.internal:5001/frrouting/frr

    - oldPrefix: registry.k8s.io/ingress-nginx
      newPrefix: host.docker.internal:5001/ingress-nginx

    - oldPrefix: registry.k8s.io/defaultbackend-amd64
      newPrefix: host.docker.internal:5001/defaultbackend-amd64

  defaultContexts:
    - name: cluster
      namespace: contexts

image:
  pullPolicy: Always
  repository: host.docker.internal:5001/kubocd

controller:
  enabled: true
  replicaCount: 1
  logger:
    mode: dev
    level: debug
  metrics:
    enabled: false
    secured: false


webhook:
  enabled: false
  replicaCount: 1
  logger:
    mode: dev
    level: debug
  metrics:
    enabled: false
    secured: false

